### ISSUE TITLE
Codeception\Util\Mink module is not configured

### ISSUE THREAD

**Issue by dstankovd** [jayhealey/Webception#37]
Hey,
I've run into the following problem... 
```
Codeception\Util\Mink module is not configured!
Provided URL can't be accessed by this driver.[curl] 6: Could not resolve host: localhost [url] http://localhost/admin/api/
```

I can open it just fine through the browser and postman.
This is my acceptance.suite.yml
```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
        - REST
    config:
        REST:
            url: 'http://localhost/admin/api/'
            timeout: 90
        PhpBrowser:
            url: 'http://localhost/admin/api/'
```
And the test is as follows: 
```
$I = new WebGuy($scenario);
$I->wantTo('Login');
$I->sendPOST('pages/login', [
        'username' => 'admin',
        'password' => 'admin'
    ]
);($I);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContains('"success": true');
```

I'm using Windows. Any help is appreciated!
